#!/usr/bin/env bash
set -uo pipefail

dir="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
have() { command -v "$1" >/dev/null 2>&1; }
say() { printf '\n\033[1m%s\033[0m\n' "$*"; }
warn() { printf 'warn: %s\n' "$*" >&2; }

if [ ! -r /etc/os-release ]; then
    echo "error: /etc/os-release not found, can't detect distro" >&2
    exit 1
fi
. /etc/os-release
id_all="$ID ${ID_LIKE:-}"
case "$id_all" in
    *arch*) os=arch ;;
    *void*) os=void ;;
    *)
        echo "error: unsupported distro '$ID' - this installer only supports Arch Linux (and derivatives) and Void Linux" >&2
        exit 1
        ;;
esac
say "Detected: $PRETTY_NAME"

sudo -v || { echo "error: need sudo for package installs" >&2; exit 1; }

if [ "$os" = arch ]; then
    say "Installing packages (pacman)..."
    sudo pacman -S --needed --noconfirm \
        base-devel rust wayland wayland-protocols fontconfig freetype2 pkgconf \
        wireplumber pipewire pipewire-pulse libpulse dbus python \
        curl playerctl brightnessctl bluez-utils kitty adwaita-fonts ttf-jetbrains-mono unzip wf-recorder
else
    say "Installing packages (xbps)..."
    sudo xbps-install -Sy \
        base-devel rust wayland-devel wayland-protocols fontconfig-devel freetype-devel pkg-config \
        wireplumber pipewire pulseaudio-utils dbus python3 \
        curl playerctl brightnessctl bluez awww xtools kitty unzip wf-recorder
fi

if ! fc-list | grep -q ": JetBrains Mono[,:]"; then
    say "Installing JetBrains Mono font..."
    font_dir="$HOME/.local/share/fonts/JetBrainsMono"
    mkdir -p "$font_dir"
    tmp_zip="$(mktemp --suffix=.zip)"
    url="$(curl -s https://api.github.com/repos/JetBrains/JetBrainsMono/releases/latest \
        | python3 -c "import json,sys; d=json.load(sys.stdin); print(next((a['browser_download_url'] for a in d['assets'] if a['name'].lower().startswith('jetbrainsmono-') and a['name'].endswith('.zip')), ''))" 2>/dev/null)"
    if [ -n "$url" ] && curl -sL "$url" -o "$tmp_zip"; then
        unzip -oq "$tmp_zip" -d "$font_dir"
        fc-cache -f "$font_dir" >/dev/null 2>&1
        say "JetBrains Mono installed to $font_dir"
    else
        warn "could not download JetBrains Mono - the clock's date line may render blank"
    fi
    rm -f "$tmp_zip"
fi

if ! have matugen; then
    say "Installing matugen via cargo..."
    cargo install matugen --locked
fi

if ! have awww; then
    if [ "$os" = arch ]; then
        say "Installing wallpaper daemon (swww)..."
        if pacman -Si swww >/dev/null 2>&1; then
            sudo pacman -S --needed --noconfirm swww
        elif have yay; then
            yay -S --needed --noconfirm swww
        elif have paru; then
            paru -S --needed --noconfirm swww
        else
            warn "swww not in official repos and no AUR helper (yay/paru) found."
            warn "install it manually: https://codeberg.org/LGFae/awww"
        fi
        if have swww && ! have awww; then
            mkdir -p "$HOME/.local/bin"
            ln -sf "$(command -v swww)" "$HOME/.local/bin/awww"
            ln -sf "$(command -v swww-daemon)" "$HOME/.local/bin/awww-daemon"
            say "symlinked awww -> swww in ~/.local/bin (make sure that's on your PATH)"
        fi
    else
        warn "awww still missing after install - check xbps-install output above"
    fi
fi

say "Setting up passwordless power actions..."
cmds=""
for bin in poweroff reboot shutdown zzz; do
    path="$(command -v "$bin" 2>/dev/null || true)"
    if [ -n "$path" ]; then
        cmds="${cmds:+$cmds, }$path"
    else
        warn "$bin not found, skipping (that power action won't work)"
    fi
done
if [ -n "$cmds" ]; then
    sudoers_file="/etc/sudoers.d/zzz-dockyrs-power"
    echo "$USER ALL=(root) NOPASSWD: $cmds" | sudo tee "$sudoers_file" >/dev/null
    sudo chmod 0440 "$sudoers_file"
    if ! sudo visudo -c >/dev/null 2>&1; then
        warn "sudoers syntax check failed, removing $sudoers_file"
        sudo rm -f "$sudoers_file"
    fi
fi

say "Building Docky.rs..."
(cd "$dir" && cargo build --release)

echo
if [ -f "$dir/target/release/dockyrs" ]; then
    say "Build OK: $dir/target/release/dockyrs"
else
    echo "error: build did not produce target/release/dockyrs" >&2
    exit 1
fi

# ----- hyprland lua drop-in -----
hypr_dir="${XDG_CONFIG_HOME:-$HOME/.config}/hypr"
lua_file="$hypr_dir/dockyrs.lua"
main_lua="$hypr_dir/hyprland.lua"
mkdir -p "$hypr_dir"

cat > "$lua_file" <<EOF
-- ----- generated by the dockyrs installer -----
local mainMod = _G.mainMod or "SUPER"
local dockyrs = "$dir/target/release/dockyrs"

hl.on("hyprland.start", function()
    hl.exec_cmd(dockyrs)
    hl.exec_cmd("$dir/target/release/dockyrs-notifyd")
    hl.exec_cmd("$dir/restore-wallpaper.sh")
end)

hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(dockyrs .. " --toggle-search"))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd(dockyrs .. " --toggle-wallpaper"))
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd(dockyrs .. " --toggle-clipboard"))
hl.bind(mainMod .. " + comma", hl.dsp.exec_cmd(dockyrs .. " --toggle-dock-menu"))
hl.bind("F8", hl.dsp.exec_cmd(dockyrs .. " --screenshot-region"))
hl.bind("F9", hl.dsp.exec_cmd(dockyrs .. " --screenshot-full"))
hl.bind(mainMod .. " + SHIFT + CTRL + 1", hl.dsp.exec_cmd(dockyrs .. " --test-notification"))
hl.bind("F10", hl.dsp.exec_cmd("$dir/record-toggle.sh"), { locked = true })
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("$dir/relaunch.sh"))
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 1%+ && " .. dockyrs .. " --osd-volume"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%- && " .. dockyrs .. " --osd-volume"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && " .. dockyrs .. " --osd-volume"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
hl.bind("code:225", hl.dsp.exec_cmd("brightnessctl -n2 set 1%+ && " .. dockyrs .. " --osd-brightness"), { locked = true, repeating = true })
hl.bind("code:224", hl.dsp.exec_cmd("brightnessctl -n2 set 1%- && " .. dockyrs .. " --osd-brightness"), { locked = true, repeating = true })

hl.layer_rule({
    name  = "dockyrs-blur",
    match = { namespace = "^dockyrs(-menu)?\$" },
    blur         = true,
    ignore_alpha = 0.0,
})
EOF
say "Wrote $lua_file"

if [ -f "$main_lua" ]; then
    if grep -q 'require("dockyrs")' "$main_lua"; then
        say "hyprland.lua already loads dockyrs"
    else
        printf '\nrequire("dockyrs")\n' >> "$main_lua"
        say "Added require(\"dockyrs\") to $main_lua"
    fi
else
    printf 'require("dockyrs")\n' > "$main_lua"
    warn "created $main_lua - if you configure Hyprland through hyprland.conf, delete it and add  require(\"dockyrs\")  wherever your Lua config lives"
fi

say "Making Docky.rs the notification daemon..."
notify_daemons="dunst mako swaync fnott wired xfce4-notifyd deadd-notification-center"

# ----- claim the name first -----
pkill -x dockyrs-notifyd >/dev/null 2>&1
sleep 0.2
setsid "$dir/target/release/dockyrs-notifyd" >/tmp/dockyrs-notifyd.log 2>&1 < /dev/null &
disown
sleep 0.3

# ----- drop the incumbent -----
if have systemctl; then
    for svc in $notify_daemons; do
        systemctl --user stop "$svc.service" >/dev/null 2>&1
    done
fi
for other in $notify_daemons; do
    pkill -x "$other" >/dev/null 2>&1 && warn "stopped $other"
done
sleep 0.4

if have busctl; then
    owner="$(busctl --user call org.freedesktop.DBus /org/freedesktop/DBus \
        org.freedesktop.DBus GetConnectionUnixProcessID s org.freedesktop.Notifications 2>/dev/null | awk '{print $2}')"
    if [ -n "$owner" ] && [ "$owner" = "$(pgrep -x dockyrs-notifyd | head -1)" ]; then
        say "dockyrs-notifyd owns org.freedesktop.Notifications"
    else
        warn "another daemon still owns notifications - mask it with: systemctl --user mask <daemon>.service"
    fi
fi

say "Starting Docky.rs..."
pkill -x dockyrs >/dev/null 2>&1
sleep 0.2
setsid "$dir/target/release/dockyrs" >/tmp/dockyrs.log 2>&1 < /dev/null &
disown
setsid "$dir/restore-wallpaper.sh" >/dev/null 2>&1 < /dev/null &
disown

if have hyprctl && hyprctl version >/dev/null 2>&1; then
    hyprctl reload >/dev/null 2>&1 && say "Hyprland reloaded - keybinds are live"
fi

say "Done - Docky.rs is running."
